name: CI - Retrain & Dockerize (MLflow Project)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  train_and_package:
    runs-on: ubuntu-latest
    environment: production


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "mlflow[extras]" pandas scikit-learn==1.5.2

      - name: Prepare MLflow tracking dir
        run: mkdir -p mlruns

      - name: Train model (python)
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
        run: python MLProject/modelling.py

      - name: Get latest MLflow run_id
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
        run: |
          python - <<'PY'
          import os
          from mlflow.tracking import MlflowClient

          client = MlflowClient()
          exps = client.search_experiments()
          latest = None

          for e in exps:
            runs = client.search_runs(
              experiment_ids=[e.experiment_id],
              order_by=["attributes.start_time DESC"],
              max_results=1
            )
            if runs:
              r = runs[0]
              if latest is None or r.info.start_time > latest.info.start_time:
                latest = r

          if latest is None:
            raise SystemExit("No MLflow runs found. Training might have failed.")

          run_id = latest.info.run_id
          with open(os.environ["GITHUB_ENV"], "a", encoding="utf-8") as f:
            f.write(f"LATEST_RUN_ID={run_id}\n")
          print("LATEST_RUN_ID=" + run_id)
          PY

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with mlflow models build-docker
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-mlflow:${{ github.sha }}"
          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV

          mlflow models build-docker \
            --model-uri "runs:/${LATEST_RUN_ID}/model" \
            --name "$IMAGE" \
            --env-manager local

      - name: Push Docker image
        run: docker push "$IMAGE_NAME"

      - name: Output Docker Hub reference
        run: echo "Docker Image pushed: $IMAGE_NAME"
